#
#
name: Firebase Hosting Merge Workflow
on:
    push:
        branches:
            - main
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
              uses: actions/checkout@v4
              run: nmp i    
              run: npm run build
              uses: FirebaseExtended/action-hosting-deploy@v0   
              with:
                repoToken: ${{ secrets.GITHUB_TOKEN }}
                firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_WEB-APP }}
                channelId: live
                projectId: web-app